namespace Portia.Lite
{
    public static class DocStrings
    {
        public static string DoubleRelation =>
            "Numerical comparison logic (Equal, GreaterThan, etc.) for filtering floating point number values.";

        public static string StringRelation =>
            "Text-based matching filters (Contains, StartsWith, etc.) used mostly for graph node / edge Type recognition.";

        public static string LogicGate =>
            "Boolean operators (AND, OR) to combine multiple conditions into a single filter.";

        public static string Severity =>
            "Defines the level of importance (Warning, Error, etc.) assigned to reports generated by Verification tasks.";
    }
}